### ISSUE TITLE
After choosing several files to view the save file is not working

### ISSUE THREAD

**Issue by Webcompose** [Ashkanph/md-to-html#3]
Good work Ashkan. I tried saving after opening several files and the files show on the screen nicely but do not save. It tries to name the merged files with the name of the first file in the collection but with and html extension. It is not a serious issue the file name but the file does not save.

**Comment by Ashkanph** [comment]
Strange. Does it log any error in the browser console? What browser do you use and what is its version?

**Comment by Webcompose** [comment]
Issue resolved. My error. I went looking in the source directory rather than the downloads folder
